# https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=python

# application: bridgy-federated

service: bounce
env: standard
runtime: python312

# default_expiration: 1h

# https://cloud.google.com/appengine/docs/standard/python3/runtime#entrypoint_best_practices
# https://docs.gunicorn.org/en/latest/settings.html#timeout
entrypoint: gunicorn --pythonpath bridgy_fed --workers 1 --threads 30 --timeout 60 -b :$PORT bounce:app

# background: https://github.com/snarfed/bridgy/issues/578
# https://github.com/snarfed/bridgy/issues/1051
automatic_scaling:
  max_idle_instances: 1
  max_instances: 20
  target_cpu_utilization: .9
  min_pending_latency: 500ms
  max_concurrent_requests: 30

inbound_services:
- warmup

# Serverless VPC Access for Memorystore memcache
# https://cloud.google.com/vpc/docs/serverless-vpc-access
vpc_access_connector:
  name: projects/bridgy-federated/locations/us-central1/connectors/bridgy-fed

env_variables:
  PDS_HOST: atproto.brid.gy
  PLC_HOST: plc.directory
  APPVIEW_HOST: api.bsky.app
  BGS_HOST: bsky.network
  MEMCACHE_HOST: '10.126.144.3'

handlers:

# static
- url: /static
  static_dir: static
  secure: always

- url: /oauth_dropins_static
  static_dir: oauth_dropins_static

- url: /fonts
  static_dir: oauth_dropins_fonts

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /admin/activity
  script: auto
  secure: always
  login: admin

# dynamic
- url: .*
  script: auto
  secure: always
